/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class CultureTrip4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CultureTrip4.class.getName());

    /**
     * Creates new form CultureTrip4
     */
    public CultureTrip4() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVFamilia1 = new javax.swing.JButton();
        btnVFamilia2 = new javax.swing.JButton();
        btnVFamilia5 = new javax.swing.JButton();
        btnVFamilia6 = new javax.swing.JButton();
        btnVFamilia7 = new javax.swing.JButton();
        btnVFamilia8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 60));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 120, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Viaje por Cultura");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        btnVFamilia1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia1.setText("<html>Semana Santa<br><small></small></html>");
        btnVFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVFamilia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 180, 100));

        btnVFamilia2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia2.setText("<html>Día de los Difuntos<br><small></small></html>");
        btnVFamilia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVFamilia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 80));

        btnVFamilia5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia5.setText("<html>Fin de año<br><small></small></html>");
        btnVFamilia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVFamilia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 120, 80));

        btnVFamilia6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia6.setText("<html>Carnaval en Cuenca<br><small></small></html>");
        btnVFamilia6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVFamilia6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 150, 100));

        btnVFamilia7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia7.setText("<html>Pase del Niño Viajero<br><small></small></html>");
        btnVFamilia7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia7ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVFamilia7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 180, 100));

        btnVFamilia8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia8.setText("<html>Festival de Luces en honor a la Virgen Morenica del Rosario<br><small></small></html>");
        btnVFamilia8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia8ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVFamilia8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 180, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        FrmPrincipal paginaPrincipal = new FrmPrincipal();
        paginaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
       CultureTrip3 culturetrip3 = new CultureTrip3();
        culturetrip3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        // TODO add your handling code here:
        CultureTrip5 culturetrip5 = new CultureTrip5();
        culturetrip5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnVFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia1ActionPerformed

    private void btnVFamilia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia2ActionPerformed

    private void btnVFamilia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia5ActionPerformed

    private void btnVFamilia6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia6ActionPerformed

    private void btnVFamilia7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia7ActionPerformed

    private void btnVFamilia8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CultureTrip4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVFamilia1;
    private javax.swing.JButton btnVFamilia2;
    private javax.swing.JButton btnVFamilia5;
    private javax.swing.JButton btnVFamilia6;
    private javax.swing.JButton btnVFamilia7;
    private javax.swing.JButton btnVFamilia8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
