/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class DescubreCuenca5 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DescubreCuenca5.class.getName());

    /**
     * Creates new form DescubreCuenca5
     */
    public DescubreCuenca5() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMuseoHorario = new javax.swing.JButton();
        btnPajaSombrero = new javax.swing.JButton();
        btnMUCuenca = new javax.swing.JButton();
        btnPumapungo = new javax.swing.JButton();
        btnArteModerno = new javax.swing.JButton();
        btnRCrespo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 60));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 120, 60));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Toda la riqueza cultural y artística de Cuenca y parte del país, se expone en interesantes y lúdicos museos de");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 580, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Museos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("la ciudad.  En la ciudad también encontramos otros espacios destinados a la difusión de la cultura como");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 580, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("galerías de arte, teatros, fundaciones, centros culturales, etc. ¡Descúbrelos!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 580, -1));

        btnMuseoHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMuseoHorario.setText("<html>Conoce sus horarios aquí<br><small></small></html>");
        btnMuseoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuseoHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnMuseoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 160, 70));

        btnPajaSombrero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPajaSombrero.setText("<html>Museo de la Paja Toquilla y el Sombrero<br><small></small></html>");
        btnPajaSombrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPajaSombreroActionPerformed(evt);
            }
        });
        jPanel1.add(btnPajaSombrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, 80));

        btnMUCuenca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMUCuenca.setText("<html>Museo de la UCuenca<br><small></small></html>");
        btnMUCuenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMUCuencaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMUCuenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 110, 100));

        btnPumapungo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPumapungo.setText("<html>Museo y parque arqueológico Pumapungo<br><small></small></html>");
        btnPumapungo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPumapungoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPumapungo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 80));

        btnArteModerno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnArteModerno.setText("<html>Museo de Arte Moderno<br><small></small></html>");
        btnArteModerno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArteModernoActionPerformed(evt);
            }
        });
        jPanel1.add(btnArteModerno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 110, 100));

        btnRCrespo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRCrespo.setText("<html>Museo Remigio Crespo<br><small></small></html>");
        btnRCrespo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCrespoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRCrespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 160, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarcuenca = new QueVisitarCuenca();
        quevisitarcuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         DescubreCuenca4 descubrecuenca4 = new DescubreCuenca4();
        descubrecuenca4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        // TODO add your handling code here:
         DescubreCuenca6 descubrecuenca6 = new DescubreCuenca6();
        descubrecuenca6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnPajaSombreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPajaSombreroActionPerformed
        // TODO add your handling code here:
        MuseoPajaToquilla museopajasombrero = new MuseoPajaToquilla();
        museopajasombrero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPajaSombreroActionPerformed

    private void btnPumapungoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPumapungoActionPerformed
        // TODO add your handling code here:
        MuseoPumapungo museopumapungo = new MuseoPumapungo();
        museopumapungo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPumapungoActionPerformed

    private void btnRCrespoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCrespoActionPerformed
        // TODO add your handling code here:
        MuseoRemigioCrespo museoremigiocrespo = new MuseoRemigioCrespo();
        museoremigiocrespo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRCrespoActionPerformed

    private void btnArteModernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArteModernoActionPerformed
        // TODO add your handling code here:
        MuseoArteModerno museoartemoderno = new MuseoArteModerno();
        museoartemoderno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnArteModernoActionPerformed

    private void btnMUCuencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMUCuencaActionPerformed
        // TODO add your handling code here:
        MuseoUCuenca museoucuenca = new MuseoUCuenca();
        museoucuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMUCuencaActionPerformed

    private void btnMuseoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuseoHorarioActionPerformed
        // TODO add your handling code here:
         HorariosMuseos horariosmuseos = new HorariosMuseos();
        horariosmuseos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMuseoHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DescubreCuenca5().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArteModerno;
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnMUCuenca;
    private javax.swing.JButton btnMuseoHorario;
    private javax.swing.JButton btnPajaSombrero;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnPumapungo;
    private javax.swing.JButton btnRCrespo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
