/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class DescubreCuenca6 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DescubreCuenca6.class.getName());

    /**
     * Creates new form DescubreCuenca6
     */
    public DescubreCuenca6() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPiedraAgua = new javax.swing.JButton();
        btnNovaqua = new javax.swing.JButton();
        btnBalRinon = new javax.swing.JButton();
        btnBalDuran = new javax.swing.JButton();
        btnAgapantos = new javax.swing.JButton();
        btnRodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 60));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 120, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Termales");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("A tan solo 15 minutos del  Centro Histórico de Cuenca, en la parroquia de Baños se encuentran aguas");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 580, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("termales, que ﬂuyen de una falla volcánica alrededor de la cual se han construido numerosos spas, balnearios");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 580, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("y establecimientos de hospedaje.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 580, -1));

        btnPiedraAgua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPiedraAgua.setText("<html>Piedra de Agua: Fuente Termal y Spa<br><small></small></html>");
        jPanel1.add(btnPiedraAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 80));

        btnNovaqua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNovaqua.setText("<html>Novaqua Spa<br><small></small></html>");
        jPanel1.add(btnNovaqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 120, 70));

        btnBalRinon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBalRinon.setText("<html>Balneario Riñón<br><small></small></html>");
        jPanel1.add(btnBalRinon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 150, 80));

        btnBalDuran.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBalDuran.setText("<html>Hosteria y Balneario Durán<br><small></small></html>");
        jPanel1.add(btnBalDuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, 80));

        btnAgapantos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgapantos.setText("<html>Hosteria Agapantos<br><small></small></html>");
        jPanel1.add(btnAgapantos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 150, 80));

        btnRodas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRodas.setText("<html>Hosteria Termal Rodas<br><small></small></html>");
        jPanel1.add(btnRodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 150, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarcuenca = new QueVisitarCuenca();
        quevisitarcuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         DescubreCuenca5 descubrecuenca5 = new DescubreCuenca5();
        descubrecuenca5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        // TODO add your handling code here:
         DescubreCuenca7 descubrecuenca7 = new DescubreCuenca7();
        descubrecuenca7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DescubreCuenca6().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgapantos;
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnBalDuran;
    private javax.swing.JButton btnBalRinon;
    private javax.swing.JButton btnNovaqua;
    private javax.swing.JButton btnPiedraAgua;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRodas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
