/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class DescubreCuenca8 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DescubreCuenca8.class.getName());

    /**
     * Creates new form DescubreCuenca8
     */
    public DescubreCuenca8() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTuri = new javax.swing.JButton();
        btnBoqueron = new javax.swing.JButton();
        btnJalshiNulti = new javax.swing.JButton();
        btnCalvario = new javax.swing.JButton();
        btnIctoCruz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 60));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 120, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Miradores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Desde lo alto Cuenca se ve inalcanzable. Desde los miradores tendrás panorámicas espectaculares de la");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 580, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ciudad. De día o de noche, Cuenca se ve majestuosa.  de Turi, El Calvario, Icto Cruz, El Boquerón y Jalshi de");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 580, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nulti.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 580, -1));

        btnTuri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTuri.setText("<html>Turi<br><small></small></html>");
        btnTuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuriActionPerformed(evt);
            }
        });
        jPanel1.add(btnTuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, 40));

        btnBoqueron.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBoqueron.setText("<html>El Boquerón<br><small></small></html>");
        btnBoqueron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoqueronActionPerformed(evt);
            }
        });
        jPanel1.add(btnBoqueron, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 120, 70));

        btnJalshiNulti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnJalshiNulti.setText("<html>Jalshi de Nulti<br><small></small></html>");
        btnJalshiNulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJalshiNultiActionPerformed(evt);
            }
        });
        jPanel1.add(btnJalshiNulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, 80));

        btnCalvario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalvario.setText("<html>Mirador El Calvario<br><small></small></html>");
        btnCalvario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalvarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalvario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 150, 80));

        btnIctoCruz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIctoCruz.setText("<html>Icto Cruz<br><small></small></html>");
        btnIctoCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIctoCruzActionPerformed(evt);
            }
        });
        jPanel1.add(btnIctoCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarcuenca = new QueVisitarCuenca();
        quevisitarcuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         DescubreCuenca7 descubrecuenca7 = new DescubreCuenca7();
        descubrecuenca7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        // TODO add your handling code here:
         DescubreCuenca9 descubrecuenca9 = new DescubreCuenca9();
        descubrecuenca9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnTuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuriActionPerformed
        // TODO add your handling code here:
        MiradorTuri turi = new MiradorTuri();
        turi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTuriActionPerformed

    private void btnBoqueronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoqueronActionPerformed
        // TODO add your handling code here:
        MiradorBoqueron boqueron = new MiradorBoqueron();
        boqueron.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoqueronActionPerformed

    private void btnJalshiNultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJalshiNultiActionPerformed
        // TODO add your handling code here:
        MiradorJalshiNulti jalshi = new MiradorJalshiNulti();
        jalshi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJalshiNultiActionPerformed

    private void btnIctoCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIctoCruzActionPerformed
        // TODO add your handling code here:
        MiradorIctoCruz icto = new MiradorIctoCruz();
        icto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIctoCruzActionPerformed

    private void btnCalvarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalvarioActionPerformed
        // TODO add your handling code here:
        MiradorElCalvario calvario = new MiradorElCalvario();
        calvario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCalvarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DescubreCuenca8().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnBoqueron;
    private javax.swing.JButton btnCalvario;
    private javax.swing.JButton btnIctoCruz;
    private javax.swing.JButton btnJalshiNulti;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTuri;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
