/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class ExperienciasTrip extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExperienciasTrip.class.getName());

    /**
     * Creates new form ExperienciasTrip
     */
    public ExperienciasTrip() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVAventuras = new javax.swing.JButton();
        btnVGastronomia = new javax.swing.JButton();
        btnVCultura = new javax.swing.JButton();
        btnVFiestas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Experiencias Trip");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 300, 70));

        btnVAventuras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVAventuras.setText("<html>Viaje por<br><small>Aventuras</small></html>");
        btnVAventuras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVAventurasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVAventuras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 110, 60));

        btnVGastronomia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVGastronomia.setText("<html>Viaje por<br><small>Gastronomía</small></html>");
        btnVGastronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVGastronomiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVGastronomia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 110, 60));

        btnVCultura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVCultura.setText("<html>Viaje por<br><small>Cultura</small></html>");
        btnVCultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVCulturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVCultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 110, 60));

        btnVFiestas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFiestas.setText("<html>Viaje por<br><small>Fiestas</small></html>");
        btnVFiestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFiestasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFiestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        FrmPrincipal paginaPrincipal = new FrmPrincipal();
        paginaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarCuenca = new QueVisitarCuenca();
        quevisitarCuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVFiestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFiestasActionPerformed
        // TODO add your handling code here:
          FiestaTrip1 fiesta = new FiestaTrip1();
        fiesta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVFiestasActionPerformed

    private void btnVGastronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVGastronomiaActionPerformed
        // TODO add your handling code here:
        FoodTrip1 food1 = new FoodTrip1();
        food1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVGastronomiaActionPerformed

    private void btnVAventurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVAventurasActionPerformed
        // TODO add your handling code here:
         AventuraTrip aventura = new AventuraTrip();
        aventura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVAventurasActionPerformed

    private void btnVCulturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVCulturaActionPerformed
        // TODO add your handling code here:
        CultureTrip1 culturetrip = new CultureTrip1();
        culturetrip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVCulturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExperienciasTrip().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVAventuras;
    private javax.swing.JButton btnVCultura;
    private javax.swing.JButton btnVFiestas;
    private javax.swing.JButton btnVGastronomia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
