/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class FoodTrip2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FoodTrip2.class.getName());

    /**
     * Creates new form FoodTrip2
     */
    public FoodTrip2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnVFamilia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVFamilia1 = new javax.swing.JButton();
        btnVFamilia2 = new javax.swing.JButton();
        btnVFamilia3 = new javax.swing.JButton();
        btnVFamilia4 = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        btnVFamilia5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 60));

        btnVFamilia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia.setText("<html>Los grills de la Calle Larga<br><small></small></html>");
        btnVFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 150, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Viaje por Gastronomía");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        btnVFamilia1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia1.setText("<html>Casa de experiencias Paccari Cuenca nueva experiencia gastronómica en la Ciudad<br><small></small></html>");
        btnVFamilia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFamilia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 230, 130));

        btnVFamilia2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia2.setText("<html>Tradición y vanguardia de la gastronomía de San Sebastián<br><small></small></html>");
        btnVFamilia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFamilia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 170, 110));

        btnVFamilia3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia3.setText("<html>Los sabores de los mercados<br><small></small></html>");
        btnVFamilia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFamilia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 140, 80));

        btnVFamilia4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia4.setText("<html>Las cascaritas de la Don Bosco<br><small></small></html>");
        btnVFamilia4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFamilia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 80));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 120, 60));

        btnVFamilia5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVFamilia5.setText("<html>La trucha del parque nacional Cajas<br><small></small></html>");
        btnVFamilia5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFamilia5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVFamilia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 170, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        FrmPrincipal paginaPrincipal = new FrmPrincipal();
        paginaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
         FoodTrip1 foodtrip1 = new FoodTrip1();
        foodtrip1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamiliaActionPerformed

    private void btnVFamilia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia1ActionPerformed

    private void btnVFamilia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia2ActionPerformed

    private void btnVFamilia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia3ActionPerformed

    private void btnVFamilia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia4ActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        // TODO add your handling code here:
        FoodTrip3 foodTrip3 = new FoodTrip3();
        foodTrip3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnVFamilia5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFamilia5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVFamilia5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FoodTrip2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVFamilia;
    private javax.swing.JButton btnVFamilia1;
    private javax.swing.JButton btnVFamilia2;
    private javax.swing.JButton btnVFamilia3;
    private javax.swing.JButton btnVFamilia4;
    private javax.swing.JButton btnVFamilia5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
