/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

/**
 *
 * @author Usuario
 */
public class HorarioMuseos2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HorarioMuseos2.class.getName());

    /**
     * Creates new form HorarioMuseos2
     */
    public HorarioMuseos2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        btnMuseoHorario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPrincipio1 = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        btnAvanzar1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel63 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        btnMuseoHorario1 = new javax.swing.JButton();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar\n");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 60));

        btnAvanzar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 120, 60));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Museo de Arte Moderno");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Entrada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" y Coronel Tálbot");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("sábados y domingos de 10:00 a 14:00");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Museos de Cuenca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Museo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Teléfonos");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Horario");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mariscal Sucre 15-27  ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("413 4900 ext 1961");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 100, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gratuito");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 50, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Lunes a viernes: 09:00 a 16:45");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 160, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 750, 10));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Casa Museo La Condamine");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 750, 10));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("La Condamine 12-112 ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("099 291 1964");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 100, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Lunes a viernes: 10:00 a 16:00");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 160, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Sábados: 10:00 a 13:00");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gratuito");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 50, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("de Paja Toquilla");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 750, 10));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Calle Larga 10-41");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("y Padre Aguirre");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 100, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("2831 569");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Lunes a viernes: 09:30 a 18:30");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 160, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("domingos de 09:30 a 15:30");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 160, -1));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Gratuito");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 50, -1));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Museo Universitario");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 750, 10));

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Av. 12 de Abril 5-199");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, -1));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("y Av. Solano");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, -1));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("405 1061");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 60, -1));

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Lunes a viernes: 08:00 a 13:00");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 160, -1));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("y de 15:00 a 18:00");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 110, -1));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Gratuito");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 50, -1));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("De La Medicina");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 750, 10));

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Av. 12 de Abril 7-55");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, -1));

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("2835 859");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 60, -1));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Lunes a viernes: 08:00 a 16:50");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 160, -1));

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Gratuito");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 50, -1));

        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Crespo Toral ");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 750, 10));

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Calle Larga y Borrero");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, -1));

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("413 4900 ext 1970");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 100, -1));

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Martes a viernes: 10:00 a 16:30");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 180, -1));

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("sábados y domingos de 09:00 a 14:00");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 210, -1));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Gratuito");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 50, -1));

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Museo del Sombrero");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("sábados: 09:30 a 17:00 y ");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 140, -1));

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Museo Historia");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, -1));

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Casa Museo Remigio");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, -1));

        btnMuseoHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMuseoHorario.setText("<html>Agrega a lugares por visitar aquí!<br><small></small></html>");
        btnMuseoHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuseoHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnMuseoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 210, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio1.setText("Ir a la página principal");
        btnPrincipio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipio1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrincipio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar1.setText("Regresar\n");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 60));

        btnAvanzar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAvanzar1.setText("Avanzar");
        btnAvanzar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAvanzar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 120, 60));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Populares De America");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Entrada");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("y Paseo Tres de Noviembre");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Museos de Cuenca");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Museo");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Dirección");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Teléfonos");
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Horario");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Hermano Miguel 3-23");
        jPanel2.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 120, -1));

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("2840 919");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 60, -1));

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Gratuito");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 50, -1));

        jLabel62.setForeground(new java.awt.Color(255, 255, 255));
        jLabel62.setText("Lunes a viernes: 08:00 a 17:00");
        jPanel2.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 160, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 750, -1));

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Aborigenes");
        jPanel2.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, -1));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 750, 10));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Hermano Miguel y Mariano Cueva");
        jPanel2.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, -1));

        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("2839 181");
        jPanel2.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, -1));

        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Lunes a viernes: 10:00 a 16:00");
        jPanel2.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 160, -1));

        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("sábado 10:00 a 13:00");
        jPanel2.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, -1));

        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Ancestral Pumapungo");
        jPanel2.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 750, 10));

        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Calle Larga 1-13 y Huayna");
        jPanel2.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, -1));

        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Cápac");
        jPanel2.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 50, -1));

        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("2831 521");
        jPanel2.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, -1));

        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Martes a viernes: 09:00 a 17:00");
        jPanel2.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 170, -1));

        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Gratuito");
        jPanel2.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 50, -1));

        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Ecuatoriana");
        jPanel2.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, -1));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 750, 10));

        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Calle Pueblo de los Quitus y");
        jPanel2.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Cultura Tolita (sector Challuabamba)");
        jPanel2.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, -1));

        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("099 250 7774");
        jPanel2.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 80, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Lunes a viernes: 09:00 a 14:30");
        jPanel2.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 160, -1));

        jLabel82.setForeground(new java.awt.Color(255, 255, 255));
        jLabel82.setText("En un rango 15,00 a 30,00 USD");
        jPanel2.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 170, -1));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 750, 10));

        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Luis Cordero y Mariscal Sucre");
        jPanel2.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 160, -1));

        jLabel85.setForeground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("2834 636/ 2826 402");
        jPanel2.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 110, -1));

        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("sábados y domingos de 09:00 a 14:00");
        jPanel2.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 210, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(255, 255, 255));
        jLabel87.setText("de 10 años libre acceso");
        jPanel2.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 110, -1));

        jLabel88.setForeground(new java.awt.Color(255, 255, 255));
        jLabel88.setText("Homero Ortega");
        jPanel2.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 120, -1));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 750, 10));

        jLabel89.setForeground(new java.awt.Color(255, 255, 255));
        jLabel89.setText("Gil Ramírez Dávalos 3-86");
        jPanel2.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, -1));

        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("280 90 00");
        jPanel2.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 60, -1));

        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("Lunes a viernes: 08:00 a 18:00");
        jPanel2.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 180, -1));

        jLabel92.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText("sábados: 09:00 a 13:00 y domingo bajo reserva");
        jPanel2.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 210, -1));

        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Gratuito");
        jPanel2.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 50, -1));

        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("Museo y Parque");
        jPanel2.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));

        jLabel95.setForeground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("sábado y domingo 10:00 a 16:00");
        jPanel2.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 180, -1));

        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("Museo Catedral Vieja");
        jPanel2.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, -1));

        jLabel97.setForeground(new java.awt.Color(255, 255, 255));
        jLabel97.setText("Museo del Sombrero");
        jPanel2.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, -1));

        btnMuseoHorario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMuseoHorario1.setText("<html>Agrega a lugares por visitar aquí!<br><small></small></html>");
        btnMuseoHorario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuseoHorario1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMuseoHorario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 210, 50));

        jLabel98.setForeground(new java.awt.Color(255, 255, 255));
        jLabel98.setText("Museo de las Artes");
        jPanel2.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, -1));

        jLabel99.setForeground(new java.awt.Color(255, 255, 255));
        jLabel99.setText("Museo de las Culturas");
        jPanel2.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        jLabel100.setText("Calle Larga 5-24 entre ");
        jPanel2.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        jLabel102.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("Estudiantes nacionales 2,00 USD");
        jPanel2.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 150, -1));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("Adultos: 4,00 USD");
        jPanel2.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 100, -1));

        jLabel104.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setText("Estudiantes extranjeros 3,00 USD");
        jPanel2.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 150, -1));

        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("Museo de la Gastronomia");
        jPanel2.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, -1));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 255, 255));
        jLabel105.setText("y domingos: 08:30 a 16:30");
        jPanel2.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 140, -1));

        jLabel106.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(255, 255, 255));
        jLabel106.setText("Sábados: 08:30 a 19:00");
        jPanel2.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 140, -1));

        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("Lunes a viernes de 09:00 a 16:00");
        jPanel2.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 180, -1));

        jLabel108.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("1,00 USD adultos y niños menores");
        jPanel2.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarcuenca = new QueVisitarCuenca();
        quevisitarcuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        HorariosMuseos horariosmuseos = new HorariosMuseos();
        horariosmuseos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        // TODO add your handling code here:
        HorariosMuseos3 horariosMuseos3 = new HorariosMuseos3();
        horariosMuseos3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnMuseoHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuseoHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMuseoHorarioActionPerformed

    private void btnPrincipio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipio1ActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarcuenca = new QueVisitarCuenca();
        quevisitarcuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipio1ActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        HorariosMuseos horariosMuseos = new HorariosMuseos();
        horariosMuseos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnAvanzar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzar1ActionPerformed
        // TODO add your handling code here:
        HorariosMuseos3 horariosMuseos3 = new HorariosMuseos3();
        horariosMuseos3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAvanzar1ActionPerformed

    private void btnMuseoHorario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuseoHorario1ActionPerformed
        // TODO add your handling code here:
        ReservaLugares reservaLugares = new ReservaLugares();
        reservaLugares.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMuseoHorario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HorarioMuseos2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnAvanzar1;
    private javax.swing.JButton btnMuseoHorario;
    private javax.swing.JButton btnMuseoHorario1;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JButton btnPrincipio1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
