/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Formatter;
import java.util.regex.*;

/**
 *
 * @author RYZEN 7
 */
public class registroUsuario extends javax.swing.JFrame {

    String barra = File.separator;
    String ubicacion = System.getProperty("user.dir")+barra+"Registros"+barra;
    
    /**
     * Creates new form registroUsuario
     */
    public registroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setExtendedState(JFrame.NORMAL);
        setResizable(false);
        setVisible(true);
        this.ocultar2.setVisible(false);
        this.ocultar3.setVisible(false);
      
    
    }
        registroUsuario(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        btnRegistrox = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtCPassword = new javax.swing.JPasswordField();
        txtApellidos = new javax.swing.JTextField();
        ver2 = new javax.swing.JLabel();
        ocultar2 = new javax.swing.JLabel();
        ver3 = new javax.swing.JLabel();
        ocultar3 = new javax.swing.JLabel();
        regresarLogin = new javax.swing.JButton();
        txtNumeroTelefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1092, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/45.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-370, -220, 650, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/141.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 740, 720));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 529));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel5.setText("Registro de Usuario");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("crear su cuenta!");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Llene los siguientes campos para");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 300, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Apellidos");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 20));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 430, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombres");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 20));

        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 430, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Correo electrónico");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Número de teléfono");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Confirmar contraseña");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 180, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Tipo de Usuario");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 20));

        comboTipoUsuario.setBackground(new java.awt.Color(204, 204, 204));
        comboTipoUsuario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        comboTipoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Usuario Turista", "Guia y Administrador" }));
        comboTipoUsuario.setBorder(null);
        jPanel2.add(comboTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 20));

        btnRegistrox.setBackground(new java.awt.Color(51, 102, 255));
        btnRegistrox.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRegistrox.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrox.setText("Registrarse");
        btnRegistrox.setBorder(null);
        btnRegistrox.setBorderPainted(false);
        btnRegistrox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroxActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 230, 40));

        txtPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtPassword.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 430, 40));

        txtCPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtCPassword.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel2.add(txtCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 430, 40));

        txtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 430, 40));

        ver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image-removebg-preview (6) (2).png"))); // NOI18N
        ver2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ver2MouseClicked(evt);
            }
        });
        jPanel2.add(ver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 30, 30));

        ocultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image-removebg-preview (7) (1).png"))); // NOI18N
        ocultar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultar2MouseClicked(evt);
            }
        });
        jPanel2.add(ocultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        ver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image-removebg-preview (6) (2).png"))); // NOI18N
        ver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ver3MouseClicked(evt);
            }
        });
        jPanel2.add(ver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 30, 30));

        ocultar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image-removebg-preview (7) (1).png"))); // NOI18N
        ocultar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultar3MouseClicked(evt);
            }
        });
        jPanel2.add(ocultar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 30, 30));

        regresarLogin.setBackground(new java.awt.Color(255, 0, 0));
        regresarLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        regresarLogin.setForeground(new java.awt.Color(255, 255, 255));
        regresarLogin.setText("Regresar");
        regresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarLoginActionPerformed(evt);
            }
        });
        jPanel2.add(regresarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 160, 40));

        txtNumeroTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtNumeroTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTelefonoActionPerformed(evt);
            }
        });
        txtNumeroTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 430, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Contraseña");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 150, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 540, 610));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/162.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  



    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    private void btnRegistroxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroxActionPerformed
  String nombres = txtNombres.getText();
    String apellidos = txtApellidos.getText();
    String email = txtEmail.getText();
    String numeroTelefono = txtNumeroTelefono.getText();
    String contraseña = new String(txtPassword.getPassword());
    String confirmarContraseña = new String(txtCPassword.getPassword());
    String tipoUsuario = comboTipoUsuario.getSelectedItem().toString();
    // Validación
    if (nombres.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese su nombre");
    } else if (apellidos.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese sus apellidos");
    } else if (email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese su correo electrónico");
    } else if (!isEmailC(email)) {
        JOptionPane.showMessageDialog(null, "El correo electrónico no es válido. Ejemplo válido: usuario@dominio.com");
    } else if (numeroTelefono.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese su número de teléfono");
    } else if (!isTelefonoValido(numeroTelefono)) {
        JOptionPane.showMessageDialog(null, "El número de teléfono no es válido. Debe tener exactamente 10 dígitos.");
    } else if (contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese su contraseña");
    } else if (!esContraseñaSegura(contraseña)) {
        JOptionPane.showMessageDialog(null, "La contraseña no cumple con los requisitos de seguridad:\n"
                + "- Mínimo 8 caracteres\n"
                + "- Al menos una mayúscula\n"
                + "- Al menos una minúscula\n"
                + "- Al menos un número\n"
                + "- Al menos un carácter especial");
    } else if (confirmarContraseña.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Confirme su contraseña");
    } else if (!contraseña.equals(confirmarContraseña)) {
        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
    } else if (tipoUsuario.equals("Seleccionar")) {
        JOptionPane.showMessageDialog(null, "Seleccione un tipo de usuario.");
    } else {
        try (FileWriter writer = new FileWriter("cuentausers.txt", true)) {
            String datosUsuario = String.format("%s,%s,%s,%s,%s,%s%n", 
                nombres, apellidos, email, numeroTelefono, contraseña, tipoUsuario);
            writer.write(datosUsuario);
            JOptionPane.showMessageDialog(null, "Registro exitoso");
            limpiar(); // Limpiar campos
            this.dispose(); // Cierra la ventana de registro
            new xd().setVisible(true); // Abre la ventana de login
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar los datos: " + e.getMessage());
        }
    }
    
    }//GEN-LAST:event_btnRegistroxActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        if(!(Character.isLetter(evt.getKeyChar()))&& !(evt.getKeyChar()==KeyEvent.VK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void ver2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver2MouseClicked
        ver2.setVisible(false);
        ocultar2.setVisible(true);
        txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_ver2MouseClicked

    private void ocultar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultar2MouseClicked
        ver2.setVisible(true);
        ocultar2.setVisible(false);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_ocultar2MouseClicked

    private void ver3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver3MouseClicked
        ver3.setVisible(false);
        ocultar3.setVisible(true);
        txtCPassword.setEchoChar((char)0);
    }//GEN-LAST:event_ver3MouseClicked

    private void ocultar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultar3MouseClicked
        ver3.setVisible(true);
        ocultar3.setVisible(false);
        txtCPassword.setEchoChar('*');
    }//GEN-LAST:event_ocultar3MouseClicked

    private void regresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarLoginActionPerformed
        // TODO add your handling code here:
      
   
        new xd().setVisible(true); // Abre la ventana de inicio de sesión
        registroUsuario.this.dispose(); // Cierra la ventana de registro
    
    }//GEN-LAST:event_regresarLoginActionPerformed

    private void txtNumeroTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTelefonoActionPerformed

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtNumeroTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Permitir solo dígitos
        if (!Character.isDigit(c)) {
            evt.consume(); // No permitir la entrada
        }
    
    }//GEN-LAST:event_txtNumeroTelefonoKeyTyped
        
    private boolean isTelefonoValido(String telefono) {
    return telefono.matches("\\d{10}");
}
public boolean isEmailC(String correox) {
    String EMAIL_PATTERN = 
        "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
    Pattern pattern = Pattern.compile(EMAIL_PATTERN);
    Matcher matcher = pattern.matcher(correox);
    return matcher.matches();
}
        
    private boolean esContraseñaSegura(String contraseña) {
    if(contraseña.length() < 8) {
        return false;
    }
    
    boolean tieneMayuscula = false;
    boolean tieneMinuscula = false;
    boolean tieneNumero = false;
    boolean tieneCaracterEspecial = false;
    
    for(char c : contraseña.toCharArray()) {
        if(Character.isUpperCase(c)) {
            tieneMayuscula = true;
        } else if(Character.isLowerCase(c)) {
            tieneMinuscula = true;
        } else if(Character.isDigit(c)) {
            tieneNumero = true;
            } else if(!Character.isLetterOrDigit(c)) {
            tieneCaracterEspecial = true;
        }
    }
    
    return tieneMayuscula && tieneMinuscula && tieneNumero && tieneCaracterEspecial;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrox;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel ocultar2;
    private javax.swing.JLabel ocultar3;
    private javax.swing.JButton regresarLogin;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtCPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroTelefono;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel ver2;
    private javax.swing.JLabel ver3;
    // End of variables declaration//GEN-END:variables
void limpiar() {
    txtNombres.setText("");
    txtApellidos.setText("");
    txtPassword.setText("");
    txtEmail.setText("");
    txtCPassword.setText("");
    txtNumeroTelefono.setText("");
    comboTipoUsuario.setSelectedIndex(0); // Reiniciar el combo box
}
}
