/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frm;
import java.io.BufferedReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class ReservaLugares extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservaLugares.class.getName());
DefaultTableModel modelo;
    private static boolean ga = false;
    /**
     * Creates new form ReservaLugares
     */
    public ReservaLugares() {
        initComponents();
        setLocationRelativeTo(null);
        mtd_prepararTabla();
         cbMuseos.setVisible(false);
    cbRestaurantes.setVisible(false);
    cbCafeterias.setVisible(false);
    cbMercados.setVisible(false);
    cbMiradores.setVisible(false);
    cbTermales.setVisible(false);
    cbPatrimonios.setVisible(false);
    cbArtesania.setVisible(false);
    cargarDatosDesdeArchivo();
    }
    private void cargarDatosDesdeArchivo() {
    try (BufferedReader reader = new BufferedReader(new FileReader("registroAventura.txt"))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split(",");
            if (datos.length == 3) {
                modelo.addRow(datos);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar los datos: " + e.getMessage());
    }
}
    private void guardarDatosEnArchivo() {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter("registroAventura.txt"))) {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String tipo = modelo.getValueAt(i, 0).toString();
            String nombre = modelo.getValueAt(i, 1).toString();
            String fecha = modelo.getValueAt(i, 2).toString();
            writer.write(tipo + "," + nombre + "," + fecha);
            writer.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(null, "Error al guardar los datos: " + e.getMessage());
    }
}
 private void mtd_prepararTabla() {
        String titulos[] = {"Tipo", "Nombre", "Fecha"};
        modelo = new DefaultTableModel(null, titulos);
        tablita.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrincipio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbRestaurantes = new javax.swing.JComboBox<>();
        txtFecha = new com.toedter.calendar.JDateChooser();
        btnAgregar = new javax.swing.JButton();
        cbMuseos = new javax.swing.JComboBox<>();
        cbCafeterias = new javax.swing.JComboBox<>();
        cbMercados = new javax.swing.JComboBox<>();
        cbTermales = new javax.swing.JComboBox<>();
        cbArtesania = new javax.swing.JComboBox<>();
        cbMiradores = new javax.swing.JComboBox<>();
        cbPatrimonios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrincipio.setText("Ir a la página principal");
        btnPrincipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planificación de lugares por visitar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("mejor recorrido por la ciudad, para ello, pulsa aquí.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 340, 20));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 100, 60));

        tablita.setBackground(new java.awt.Color(204, 255, 153));
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablita);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 720, 180));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Museos", "Restaurantes", "Cafeterias", "Mercados", "Miradores", "Termales", "Patrimonios", "Artesania", " ", " " }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lugar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        cbRestaurantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Tiestos restaurante", "Dos Sucres", "Negroni Cuenca", "El Mercado", "Cocotte - Mansión Alcázar ", "Restaurante Santa Lucía", "Capitán Restaurante", "La María Cocina Libre", "La Chichería", "Punjabi Rasoi" }));
        jPanel1.add(cbRestaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 100, 60));

        cbMuseos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Museo de Arte Moderno", "Casa Museo La Condamine", "Museo del Sombrero de Paja Toquilla", "Museo Universitario", "Museo Historia de La Medicina", "Casa Museo Remigio Crespo Toral ", "Museo de las Artes Populares De America", "Museo de las Culturas Aborigenes", "Museo y Parque Ancestral Pumapungo", "Museo de la Gastronomia Ecuatoriana", "Museo Catedral Vieja", "Museo del Sombrero Homero Ortega", "Museo Municipal de la Paja Toquilla y el Sombrero", "Museo de La Ciudad", "Amalia Uriguen", "Museo del Cacao", "Museo de las Conceptas", "Museo de antigüedades “Zoila Quezada”" }));
        jPanel1.add(cbMuseos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbCafeterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Café de la Sucre", "Café del Zaguán", "Café de San Sebas", "Dulcet", "Paccari" }));
        jPanel1.add(cbCafeterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbMercados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Mercado 12 de Abril", "Mercado 10 de Agosto", "Mercado 9 de Octubre", "Mercado 3 de Noviembre" }));
        jPanel1.add(cbMercados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbTermales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Piedra de Agua", "Hosteria y Balneario Durán", "Hosteria Termal Rodas", "Novaqua Spa", "Hosteria Agapantos", "Balneario Riñón" }));
        jPanel1.add(cbTermales, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbArtesania.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "PRAC - EDEC", "CEMUART", "Plaza Rotary", "CIDAP" }));
        jPanel1.add(cbArtesania, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbMiradores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Turi", "Icto Cruz", "El Boquerón", "Jalshi de Nulti", "Mirador El Calvario" }));
        jPanel1.add(cbMiradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        cbPatrimonios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Casa Patrimonial de La Lira", "Casa Patrimonial Quinta Bolívar", "Casa Patrimonial de las Posadas", "Casa Patrimonial Municipal del Alfarero", "Casa Patrimonial Chaguarchimbana", "Casa Patrimonial Municipal del Artista", "Antigua Escuela Central", "Casa Patrimonial Márquez" }));
        jPanel1.add(cbPatrimonios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Elija el tipo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        btnOrdenar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnOrdenar.setText("Ordenar por tipo");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 160, 60));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seleccione el lugar que desea guardar en sus proximas visitas para agregarlo a la tabla:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 480, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Es recomendable que busques un guía que te ayude a tener un");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 340, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("Ver guías");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipioActionPerformed
        // TODO add your handling code here:
        QueVisitarCuenca quevisitarcuenca = new QueVisitarCuenca();
        quevisitarcuenca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrincipioActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablita.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        modelo.removeRow(filaSeleccionada);
        guardarDatosEnArchivo(); // Guardar datos en el archivo
        JOptionPane.showMessageDialog(null, "Fila eliminada exitosamente.");
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione una fila para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
 if (cbTipo.getSelectedItem() != null && cbTipo.getSelectedItem().toString().length() > 0) {
        String tipoLugar = cbTipo.getSelectedItem().toString();
        String lugarSeleccionado = "";
        if ("Museos".equals(tipoLugar)) {
            lugarSeleccionado = cbMuseos.getSelectedItem().toString();
        } else if ("Restaurantes".equals(tipoLugar)) {
            lugarSeleccionado = cbRestaurantes.getSelectedItem().toString();
        } else if ("Cafeterias".equals(tipoLugar)) {
            lugarSeleccionado = cbCafeterias.getSelectedItem().toString();
        } else if ("Mercados".equals(tipoLugar)) {
            lugarSeleccionado = cbMercados.getSelectedItem().toString();
        } else if ("Miradores".equals(tipoLugar)) {
            lugarSeleccionado = cbMiradores.getSelectedItem().toString();
        } else if ("Termales".equals(tipoLugar)) {
            lugarSeleccionado = cbTermales.getSelectedItem().toString();
        } else if ("Patrimonios".equals(tipoLugar)) {
            lugarSeleccionado = cbPatrimonios.getSelectedItem().toString();
        } else if ("Artesania".equals(tipoLugar)) {
       lugarSeleccionado = cbArtesania.getSelectedItem().toString();
        }
        
        // Verificar que se haya seleccionado una fecha
        if (txtFecha.getDate() != null) {
            String fechaVisita = txtFecha.getDate().toString();
            String nuevaFila[] = {tipoLugar, lugarSeleccionado, fechaVisita};
            modelo.addRow(nuevaFila);
            guardarDatosEnArchivo();
            mtd_limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fecha de visita");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese el tipo de lugar a visitar");
    }     
      
    }//GEN-LAST:event_btnAgregarActionPerformed
private void mtd_limpiar() {
        cbTipo.setSelectedIndex(0);
        cbMuseos.setSelectedIndex(0);
        cbRestaurantes.setSelectedIndex(0);
        txtFecha.setDate(null);
    }
    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        String opcionSeleccionada = (String) cbTipo.getSelectedItem();
    
    cbMuseos.setVisible(false);
    cbRestaurantes.setVisible(false);
    cbCafeterias.setVisible(false);
    cbMercados.setVisible(false);
    cbMiradores.setVisible(false);
    cbTermales.setVisible(false);
    cbPatrimonios.setVisible(false);
    cbArtesania.setVisible(false);
    
    switch (opcionSeleccionada) {
        case "Museos":
            cbMuseos.setVisible(true);
            break;
        case "Restaurantes":
            cbRestaurantes.setVisible(true);
            break;
            case "Cafeterias":
            cbCafeterias.setVisible(true);
            break;
        case "Mercados":
            cbMercados.setVisible(true);
            break;
        case "Miradores":
            cbMiradores.setVisible(true);
            break;
        case "Termales":
            cbTermales.setVisible(true);
            break;
        case "Patrimonios":
            cbPatrimonios.setVisible(true);
            break;
        case "Artesania":
            cbArtesania.setVisible(true);
            break;
    }
    }//GEN-LAST:event_cbTipoActionPerformed
private void ordenarPorTipo() {
    int n = modelo.getRowCount();
    boolean intercambiado;

    // Método de burbuja para ordenar
    do {
        intercambiado = false;
        for (int i = 0; i < n - 1; i++) {
            String tipo1 = modelo.getValueAt(i, 0).toString();
            String tipo2 = modelo.getValueAt(i + 1, 0).toString();
            if (tipo1.compareTo(tipo2) > 0) {
                // Intercambiar filas
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                    Object temp = modelo.getValueAt(i, j);
                    modelo.setValueAt(modelo.getValueAt(i + 1, j), i, j);
                    modelo.setValueAt(temp, i + 1, j);
                }
                intercambiado = true;
            }
        }
        n--; // Reducir el tamaño del array
    } while (intercambiado);
}

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        ordenarPorTipo();
    JOptionPane.showMessageDialog(null, "Datos ordenados por tipo de lugar.");
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VerGuias guias = new VerGuias();
        guias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReservaLugares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnPrincipio;
    private javax.swing.JComboBox<String> cbArtesania;
    private javax.swing.JComboBox<String> cbCafeterias;
    private javax.swing.JComboBox<String> cbMercados;
    private javax.swing.JComboBox<String> cbMiradores;
    private javax.swing.JComboBox<String> cbMuseos;
    private javax.swing.JComboBox<String> cbPatrimonios;
    private javax.swing.JComboBox<String> cbRestaurantes;
    private javax.swing.JComboBox<String> cbTermales;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablita;
    private com.toedter.calendar.JDateChooser txtFecha;
    // End of variables declaration//GEN-END:variables
}
